name: hello-rust-ci
  
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: "Checkout repository"
          uses: actions/checkout@v3
        - name: "Install Rust Toolchains"
          uses: "dtolnay/rust-toolchain@stable"
        - name: "cargo build --release"
          run: cargo build --release
